CREATE TABLE products
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255)                            NOT NULL,
    description     VARCHAR(255)                            NOT NULL,
    price           DECIMAL,
    remaining_stock INTEGER,
    CONSTRAINT pk_products PRIMARY KEY (id)
);