CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tracking_number VARCHAR(50)                         NOT NULL,
    order_value DECIMAL                                 NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    customer_id BIGINT,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT uc_order_tracking_number UNIQUE (tracking_number);