CREATE TABLE product_images
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT,
    ima_url    VARCHAR(255)                            NOT NULL,
    img_order  INTEGER,
    main_img   BOOLEAN,
    alt_text   VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_product_images PRIMARY KEY (id)
);

ALTER TABLE product_images
    ADD CONSTRAINT FK_PRODUCT_IMAGES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);