CREATE TABLE ratings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment    VARCHAR(255)                            NOT NULL,
    rating     INTEGER                                 NOT NULL,
    posted_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    product_id BIGINT,
    CONSTRAINT pk_ratings PRIMARY KEY (id)
);

ALTER TABLE ratings
    ADD CONSTRAINT FK_RATINGS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE ratings
    ADD CONSTRAINT FK_RATINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);